[package]
name = "aoc_2023"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc_lib = { path = "../aoc_lib" }
itertools = "0.14.0"
num-traits = "0.2.19"
petgraph = "0.8.3"
polynomial = "0.2.6"
rayon = "1.10.0"
rustworkx-core = "0.17.1"
#z3 = { version = "0.12.1", features = ["static-link-z3"] }
